apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "okdp-ui.fullname" . }}
  labels:
    {{- include "okdp-ui.labels" . | nindent 4 }}
data:
  app.config.json: |-
    {{ toJson .Values.ui | indent 4 }}
