# For more properties: https://github.com/OKDP/okdp-ui/blob/main/public/config/app.config.json
ui:
  auth:
    provider: oauth2
    oauth2:
      issuer: http://keycloak:7080/realms/master
      redirectUri: http://okdp-ui.okdp.sandbox/index.html
      silentRefreshRedirectUri: http://okdp-ui.okdp.sandbox/silent-refresh.html
      clientId: public-oidc-client
      responseType: code
      scope: openid profile email offline_access roles
      showDebugInformation: true
      requireHttps: false
  okdpApi:
    apiUrl: https://okdp-server.okdp.sandbox/api/v1
    swaggerUrl: https://okdp-server.okdp.sandbox/swagger
  catalogs:
    services:
    - all
    kad:
    - all

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: okdp-ui.okdp.sandbox
      paths:
        - path: /
          pathType: Prefix

