#
# Copyright 2026 The OKDP Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# For more properties: https://github.com/OKDP/okdp-ui/blob/main/public/config/app.config.json
ui:
  auth:
    provider: oauth2
    oauth2:
      issuer: http://keycloak:7080/realms/master
      redirectUri: http://okdp-ui.okdp.sandbox/index.html
      silentRefreshRedirectUri: http://okdp-ui.okdp.sandbox/silent-refresh.html
      clientId: public-oidc-client
      responseType: code
      scope: openid profile email offline_access roles
      showDebugInformation: true
      requireHttps: false
  okdpApi:
    apiUrl: https://okdp-server.okdp.sandbox/api/v1
    swaggerUrl: https://okdp-server.okdp.sandbox/swagger
  submission:
    # -- Set to 'git' to push KuboCD releases to Git, or 'kubernetes' to apply directly to the cluster.
    mode: git
  catalogs:
    services:
    - all
    kad:
    - all

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: okdp-ui.okdp.sandbox
      paths:
        - path: /
          pathType: Prefix

